/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { IPausableStream } from "./IPausableStream";

export class IPausableStreamFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPausableStream {
    return new Contract(address, _abi, signerOrProvider) as IPausableStream;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startTime",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deposit",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "duration",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ratePerSecond",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isActive",
        type: "bool"
      }
    ],
    name: "PausableStreamCreated",
    type: "event"
  }
];
