/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PausableStreamInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "STREAM_CONTROLLER()": FunctionFragment;
    "STREAM_CREATOR()": FunctionFragment;
    "canWithdrawFunds(uint256,uint256,address)": FunctionFragment;
    "createStream(address,uint256,address,uint256,uint256)": FunctionFragment;
    "getPausableStream(uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getRoleMember(bytes32,uint256)": FunctionFragment;
    "getRoleMemberCount(bytes32)": FunctionFragment;
    "getStream(uint256)": FunctionFragment;
    "getStreamTokenAddress(uint256)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isStreamActive(uint256)": FunctionFragment;
    "nextStreamId()": FunctionFragment;
    "owner()": FunctionFragment;
    "pauseStream(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "startStream(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw(uint256,uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STREAM_CONTROLLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STREAM_CREATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canWithdrawFunds",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPausableStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMember",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamTokenAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isStreamActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextStreamId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "startStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STREAM_CONTROLLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STREAM_CREATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canWithdrawFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPausableStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStreamTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isStreamActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextStreamId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PausableStreamCreated(uint256,uint256,uint256,uint256,uint256,bool)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PausableStreamCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export class PausableStream extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PausableStreamInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    STREAM_CONTROLLER(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "STREAM_CONTROLLER()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    STREAM_CREATOR(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "STREAM_CREATOR()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    canWithdrawFunds(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "canWithdrawFunds(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createStream(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "createStream(address,uint256,address,uint256,uint256)"(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    getPausableStream(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      duration: BigNumber;
      durationElapsed: BigNumber;
      durationRemaining: BigNumber;
      deposit: BigNumber;
      balanceAccrued: BigNumber;
      startTime: BigNumber;
      isRunning: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
    }>;

    "getPausableStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      duration: BigNumber;
      durationElapsed: BigNumber;
      durationRemaining: BigNumber;
      deposit: BigNumber;
      balanceAccrued: BigNumber;
      startTime: BigNumber;
      isRunning: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
    }>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getStream(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      sender: string;
      recipient: string;
      deposit: BigNumber;
      tokenAddress: string;
      startTime: BigNumber;
      stopTime: BigNumber;
      remainingBalance: BigNumber;
      ratePerSecond: BigNumber;
      0: string;
      1: string;
      2: BigNumber;
      3: string;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
    }>;

    "getStream(uint256)"(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      sender: string;
      recipient: string;
      deposit: BigNumber;
      tokenAddress: string;
      startTime: BigNumber;
      stopTime: BigNumber;
      remainingBalance: BigNumber;
      ratePerSecond: BigNumber;
      0: string;
      1: string;
      2: BigNumber;
      3: string;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
    }>;

    getStreamTokenAddress(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getStreamTokenAddress(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isStreamActive(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "isStreamActive(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    nextStreamId(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "nextStreamId()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    pauseStream(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "pauseStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    startStream(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "startStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  STREAM_CONTROLLER(overrides?: CallOverrides): Promise<string>;

  "STREAM_CONTROLLER()"(overrides?: CallOverrides): Promise<string>;

  STREAM_CREATOR(overrides?: CallOverrides): Promise<string>;

  "STREAM_CREATOR()"(overrides?: CallOverrides): Promise<string>;

  canWithdrawFunds(
    _streamId: BigNumberish,
    _amount: BigNumberish,
    _who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "canWithdrawFunds(uint256,uint256,address)"(
    _streamId: BigNumberish,
    _amount: BigNumberish,
    _who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createStream(
    _recipient: string,
    _deposit: BigNumberish,
    _tokenAddress: string,
    _duration: BigNumberish,
    _startTime: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "createStream(address,uint256,address,uint256,uint256)"(
    _recipient: string,
    _deposit: BigNumberish,
    _tokenAddress: string,
    _duration: BigNumberish,
    _startTime: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  getPausableStream(
    _streamId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    duration: BigNumber;
    durationElapsed: BigNumber;
    durationRemaining: BigNumber;
    deposit: BigNumber;
    balanceAccrued: BigNumber;
    startTime: BigNumber;
    isRunning: boolean;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: boolean;
  }>;

  "getPausableStream(uint256)"(
    _streamId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    duration: BigNumber;
    durationElapsed: BigNumber;
    durationRemaining: BigNumber;
    deposit: BigNumber;
    balanceAccrued: BigNumber;
    startTime: BigNumber;
    isRunning: boolean;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: boolean;
  }>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getRoleAdmin(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMember(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getRoleMember(bytes32,uint256)"(
    role: BytesLike,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleMemberCount(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getRoleMemberCount(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStream(
    streamId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    sender: string;
    recipient: string;
    deposit: BigNumber;
    tokenAddress: string;
    startTime: BigNumber;
    stopTime: BigNumber;
    remainingBalance: BigNumber;
    ratePerSecond: BigNumber;
    0: string;
    1: string;
    2: BigNumber;
    3: string;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
  }>;

  "getStream(uint256)"(
    streamId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    sender: string;
    recipient: string;
    deposit: BigNumber;
    tokenAddress: string;
    startTime: BigNumber;
    stopTime: BigNumber;
    remainingBalance: BigNumber;
    ratePerSecond: BigNumber;
    0: string;
    1: string;
    2: BigNumber;
    3: string;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
  }>;

  getStreamTokenAddress(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getStreamTokenAddress(uint256)"(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "grantRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isStreamActive(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "isStreamActive(uint256)"(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  nextStreamId(overrides?: CallOverrides): Promise<BigNumber>;

  "nextStreamId()"(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  pauseStream(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "pauseStream(uint256)"(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "renounceRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  startStream(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "startStream(uint256)"(
    _streamId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    _streamId: BigNumberish,
    _amount: BigNumberish,
    _who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(uint256,uint256,address)"(
    _streamId: BigNumberish,
    _amount: BigNumberish,
    _who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    STREAM_CONTROLLER(overrides?: CallOverrides): Promise<string>;

    "STREAM_CONTROLLER()"(overrides?: CallOverrides): Promise<string>;

    STREAM_CREATOR(overrides?: CallOverrides): Promise<string>;

    "STREAM_CREATOR()"(overrides?: CallOverrides): Promise<string>;

    canWithdrawFunds(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canWithdrawFunds(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    createStream(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "createStream(address,uint256,address,uint256,uint256)"(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPausableStream(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      duration: BigNumber;
      durationElapsed: BigNumber;
      durationRemaining: BigNumber;
      deposit: BigNumber;
      balanceAccrued: BigNumber;
      startTime: BigNumber;
      isRunning: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
    }>;

    "getPausableStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      duration: BigNumber;
      durationElapsed: BigNumber;
      durationRemaining: BigNumber;
      deposit: BigNumber;
      balanceAccrued: BigNumber;
      startTime: BigNumber;
      isRunning: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: boolean;
    }>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStream(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      sender: string;
      recipient: string;
      deposit: BigNumber;
      tokenAddress: string;
      startTime: BigNumber;
      stopTime: BigNumber;
      remainingBalance: BigNumber;
      ratePerSecond: BigNumber;
      0: string;
      1: string;
      2: BigNumber;
      3: string;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
    }>;

    "getStream(uint256)"(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      sender: string;
      recipient: string;
      deposit: BigNumber;
      tokenAddress: string;
      startTime: BigNumber;
      stopTime: BigNumber;
      remainingBalance: BigNumber;
      ratePerSecond: BigNumber;
      0: string;
      1: string;
      2: BigNumber;
      3: string;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
    }>;

    getStreamTokenAddress(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getStreamTokenAddress(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isStreamActive(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isStreamActive(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nextStreamId(overrides?: CallOverrides): Promise<BigNumber>;

    "nextStreamId()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    pauseStream(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "pauseStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    startStream(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "startStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    PausableStreamCreated(
      id: null,
      startTime: null,
      deposit: null,
      duration: null,
      ratePerSecond: null,
      isActive: null
    ): EventFilter;

    RoleAdminChanged(
      role: BytesLike | null,
      previousAdminRole: BytesLike | null,
      newAdminRole: BytesLike | null
    ): EventFilter;

    RoleGranted(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): EventFilter;

    RoleRevoked(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): EventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    STREAM_CONTROLLER(overrides?: CallOverrides): Promise<BigNumber>;

    "STREAM_CONTROLLER()"(overrides?: CallOverrides): Promise<BigNumber>;

    STREAM_CREATOR(overrides?: CallOverrides): Promise<BigNumber>;

    "STREAM_CREATOR()"(overrides?: CallOverrides): Promise<BigNumber>;

    canWithdrawFunds(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "canWithdrawFunds(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createStream(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "createStream(address,uint256,address,uint256,uint256)"(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    getPausableStream(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPausableStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStream(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getStream(uint256)"(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStreamTokenAddress(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getStreamTokenAddress(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isStreamActive(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "isStreamActive(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    nextStreamId(overrides?: CallOverrides): Promise<BigNumber>;

    "nextStreamId()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    pauseStream(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "pauseStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    startStream(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "startStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdraw(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    STREAM_CONTROLLER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "STREAM_CONTROLLER()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    STREAM_CREATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "STREAM_CREATOR()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canWithdrawFunds(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "canWithdrawFunds(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createStream(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "createStream(address,uint256,address,uint256,uint256)"(
      _recipient: string,
      _deposit: BigNumberish,
      _tokenAddress: string,
      _duration: BigNumberish,
      _startTime: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    getPausableStream(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPausableStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleMember(bytes32,uint256)"(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleMemberCount(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleMemberCount(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStream(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getStream(uint256)"(
      streamId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStreamTokenAddress(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getStreamTokenAddress(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isStreamActive(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "isStreamActive(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    nextStreamId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nextStreamId()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pauseStream(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "pauseStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    startStream(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "startStream(uint256)"(
      _streamId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(uint256,uint256,address)"(
      _streamId: BigNumberish,
      _amount: BigNumberish,
      _who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
